lamin_cli/_transform.py

- https://github.com/laminlabs/nbproject/pull/277

🚸 Init transform versions at 1

---

lamin_cli/__main__.py
lamin_cli/_cache.py
lamin_cli/_migration.py
pyproject.toml

Better comprehensibility for available commands.

🏗️ Use click for CLI

---

lamin_cli/_transform.py

- Notebook output now a folder with index.html and image assets.
- Remove images from the final HTML (un-inline) into their own file.
Todo:
- CSS minify needs to be run with node.

Faster notebook

---

tests/test_save_notebooks.py

For https://github.com/laminlabs/lamindb/pull/1518

New source code hash

---

tests/conftest.py
tests/notebooks/with-title-and-initialized-consecutive.ipynb
tests/notebooks/with-title-and-initialized-non-consecutive.ipynb
tests/scripts/initialized-no-git-sync.py
tests/scripts/initialized.py
tests/test_save_notebooks.py
tests/test_save_scripts.py

We'd like to be able to run the tests against any instance.

♻️ Use auto-connect in tests

---

lamin_cli/__main__.py

Fixes https://github.com/laminlabs/lamin-cli/issues/55
```
⋊> ~/P/lamin-cli on feature/order ⨯ lamin --help                                                                                                                           (lamindb) 10:58:51
Usage: lamin [OPTIONS] COMMAND [ARGS]...                                                                                                                                                    
Configure LaminDB and perform simple actions.                                                                                                                                               
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```

Add command custom order

---

lamin_cli/_save.py
tests/notebooks/with-title-and-initialized-consecutive.ipynb
tests/notebooks/with-title-and-initialized-non-consecutive.ipynb
tests/scripts/run-track-and-finish-sync-git.py
tests/scripts/run-track-and-finish.py
tests/test_save_notebooks.py
tests/test_save_scripts.py

- https://github.com/laminlabs/lamindb/pull/1816

🚚 Rename `ln.track()` to `ln.context.track()`

---

lamin_cli/__main__.py
lamin_cli/_get.py
tests/test_save_scripts.py

- https://github.com/laminlabs/lamindb/pull/1901

✨ Get entity by key or uid

---

tests/test_cli.py

https://github.com/laminlabs/lamindb-setup/pull/853

✅ Test re-login

---

lamin_cli/__main__.py

- https://github.com/laminlabs/lamindb/pull/1945

🚸 Simplify CLI commands

---

lamin_cli/__main__.py
lamin_cli/_load.py
lamin_cli/_migration.py
lamin_cli/_settings.py
tests/test_get.py
tests/test_load.py
tests/test_migrate.py
tests/test_save_notebooks.py
tests/test_save_scripts.py

https://github.com/laminlabs/pfizer-lamin-usage/issues/25#issuecomment-2367987060

🚸 `lamin load` → `lamin connect` & `lamin get` → `lamin load`

---

tests/scripts/run-track-with-params.py
tests/test_save_scripts.py

- https://github.com/laminlabs/lamindb/pull/1989

💄 Prettify track logging

---

lamin_cli/_load.py
lamin_cli/_save.py
tests/test_save_notebooks.py
tests/test_save_scripts.py

See https://github.com/laminlabs/lamindb/pull/1994

🚸 Improve `lamin load` for notebooks & scripts

---

lamin_cli/_cache.py

For https://github.com/laminlabs/lamindb-setup/pull/875

✨ Allow lamin cache set with non-existing directories

---

lamin_cli/_load.py

https://github.com/laminlabs/pfizer-lamin-usage/issues/45

🐛 Use shutil.move instead of Path.rename

---

lamin_cli/__main__.py

🐛 Fix save sphinx references

---

lamin_cli/_load.py
tests/test_load.py

Fix https://github.com/laminlabs/pfizer-lamin-usage/issues/58

🐛 Fix loading artifact by key and give clear errors if no artifacts or transforms found

---

lamin_cli/_save.py

✨ Improve save message

---

lamin_cli/_load.py
lamin_cli/_save.py
tests/scripts/run-track-and-finish.py
tests/test_parse_uid_from_code.py
tests/test_save_notebooks.py
tests/test_save_scripts.py

Needed for
- https://github.com/laminlabs/lamindb/pull/2308

🚸 Minimal `ln.track()` 2

---

lamin_cli/__main__.py
lamin_cli/_load.py
lamin_cli/_save.py

https://github.com/laminlabs/lamindb-setup/pull/923

⚡️ Do not reload lamindb on lamin connect

---

lamin_cli/__main__.py
tests/test_load.py

See:
- https://github.com/laminlabs/lamindb/pull/2563

✨ Add `lamin get` for artifacts

---

lamin_cli/_load.py
tests/test_load.py

See:
- https://github.com/laminlabs/lamindb/pull/2563
Supersedes:
- https://github.com/laminlabs/lamin-cli/pull/119

✨ Add `lamin load` for collections

---

lamin_cli/__main__.py

- https://github.com/laminlabs/lamindb-setup/pull/1002

♻️ Default to current working directory during `lamin init` and drop `--schema` arg

---

lamin_cli/__main__.py
lamin_cli/_save.py
tests/test_save_notebooks.py

- https://github.com/laminlabs/lamindb/pull/2614

✨ Enable to pass the stem uid to lamin save

---

lamin_cli/__main__.py
lamin_cli/_save.py
tests/core/test_save_files.py
tests/core/test_save_scripts.py

Example: Given a valid project name "my_project".
```
lamin save ./my_table.csv --key my_tables/my_table.csv --project my_project
```

✨ Enable labeling with project during `lamin save`

---

lamin_cli/__main__.py

For:
- https://github.com/laminlabs/lamindb/pull/2948

⚡️ Speed up `lamin connect`

---

lamin_cli/_migration.py

- https://github.com/laminlabs/lamindb-setup/pull/1116

✨ Enable reverting database migrations

---

lamin_cli/__init__.py
lamin_cli/__main__.py
lamin_cli/_delete.py

Follow-up to:
- https://github.com/laminlabs/lamin-cli/pull/153

♻️ Expose main commands as functions on root API
